site:
  title: Redpanda Docs
  start_page: custom:ROOT:index.adoc
  url: http://localhost:8000
urls:
  html_extension_style: indexify
  latest_version_segment: 'current'
output:
  clean: true
content:
  sources:
  - url: ../custom-doc
    branches: HEAD
ui:
  bundle:
    url: https://github.com/redpanda-data/docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  extensions:
    - ./scripts/hello-macro.js
  attributes:
    attribute-missing: skip
